---
title: "Drake"
output: html_notebook
---

Baseado en 

https://ropenscilabs.github.io/drake-manual/index.html



## Carga de librerías

```{r, echo=FALSE, error=FALSE}
library(drake)
library(dplyr)
library(ggplot2)
```


## Funcións de traballo

```{r}
grafica <- function(datos) {
  ggplot(datos, aes(x = Petal.Width, fill = Species)) +
    geom_histogram()
}
```


## Creación do plan

```{r}

meu_plan <- drake_plan(
 
  data = iris %>%
    mutate(Species = forcats::fct_inorder(Species)),
  hist = grafica(data),
  fit = lm(Sepal.Width ~ Petal.Width + Species, data)
)
meu_plan # só é para visualizalo plan de traballo, non fai nada
```


## Lanzamento do plan

```{r}
make(meu_plan) # executa o plan de traballo e crea os "targets"

config <- drake_config(meu_plan) # non é necesario, é para ver o funcionamento interno de plan
vis_drake_graph(config) # gráfico do plan

```



## Lectura e recuperación de "targets"

```{r, echo= TRUE}
readd(data) # Leer un "target"
g<-readd(hist)
loadd(hist)
loadd() ## Carga tódolos targets 
```



## Modificación da función

```{r}
grafica <- function(datos) {
  ggplot(datos, aes(x = Petal.Width, fill = Species)) +
    geom_histogram(binwidth = 30) +
    theme_gray(20)
}
```


```{r}
config <- drake_config(meu_plan)
vis_drake_graph(config) # Visualizalos cambios

make(meu_plan) # recreo o plan, xa que está desactualizado

config <- drake_config(meu_plan)
vis_drake_graph(config) # Visualizalos cambios
```
## Escalabilidade
Por información, drake ten ferramentas para lanzar traballos de computación avanzada (HPC)
